language: r

r:
  - release


os:
  - linux

cache: packages

before_install:
  - Rscript -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
  - Rscript -e 'remotes::install_deps(dependencies = TRUE)'

script:
  - R CMD build .
  - R CMD check *tar.gz --no-manual --as-cran

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: always
