name: R-CMD-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - {os: ubuntu-latest, r: 'devel'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel'}
          - {os: macOS-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        run: Rscript -e 'install.packages("remotes"); remotes::install_deps(dependencies = TRUE)'

      - name: Run R CMD check
        run: Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual --as-cran", error_on = "warning")'

      - name: Upload results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: R-CMD-check-results
          path: R-CMD-check/*.Rcheck/
